Sources/FigmaExport/Loaders/ImagesLoader.swift
Sources/FigmaExport/Subcommands/ExportImages.swift
Sources/FigmaExportCore/Image.swift
Sources/XcodeExport/XcodeImagesExporter.swift

The `figma-export images` is broken for Android.
The bug was caused by this [PR(supporting device idiom)](https://github.com/RedMadRobot/figma-export/pull/37).
The `loadPNGImages` method was changed to return `ImagePack.images`, but the `exportAndroidRasterImages` only accept `ImagePack.individualScales` so that no image will be exported. 
- Skip idiom checking if target platform is `Android`.
- Update `exportAndroidRasterImages` type checking.
- Update `makeRemoteFiles` to get `scale` from `Image`.
- Remove `individualScales` case. The case is not used.

[BUG] Can't export images to Android.

---

Sources/FigmaExport/Subcommands/ExportImages.swift

Dark files were using the light directory url

Fixed directory creation of dark svg images

---

Sources/FigmaExport/Output/VectorDrawableConverter.swift
Sources/FigmaExport/Subcommands/ExportIcons.swift
Sources/FigmaExport/Subcommands/ExportImages.swift

I encountered a problem with exporting icons to XML for android. In case there are unsupported XML-Tags in the SVG files for the vd-tool it only tells you that there was an error. But it does not tell you in which file. So it is pretty hard to see which assets in Figma are not built correctly.
This is a suggestion to start a separate process for each file, which makes it possible to read from the logs, which file had issues while converting.
The downside is, that starting a process for each file makes the whole thing take way longer. A proper solution would probably be to adjust the vd-tool, which is not easily doable, as this tool is also just a packaging of the Android Studio VectorDrawable CLI tool.
Maybe you have a suggestion to improve this behavior.

Start separate process per file to improve logging

---

Sources/FigmaExport/Input/FigmaExportOptions.swift

The `figma-export` commands are not working.
It returns this error for subcommands.
```
Error: Missing expected argument
Usage: figma-export (images, icons) [--input <input>] [<filter>]
See 'figma-export (images, icons) --help' for more information.
```
I found out that the `access_token` needs to be defined as `String!`, otherwise it will take it as required argument.

Fixed “Error: Missing expected argument”

---

Sources/FigmaAPI/Model/Node.swift
Sources/FigmaExport/Loaders/ColorsLoader.swift

Hi there
When I run `figma-export colors` on my project, there's a decoding error as follows:
```
$ figma-export --version
0.18.6
$ figma-export colors -i figma-export.yaml 
2020-12-29T13:13:30+0900 info com.redmadrobot.figma-export : Using FigmaExport to export colors.
2020-12-29T13:13:30+0900 info com.redmadrobot.figma-export : Fetching colors. Please wait...
Error: keyNotFound(CodingKeys(stringValue: "color", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "nodes", intValue: nil), _JSONKey(stringValue: "1:66", intValue: nil), CodingKeys(stringValue: "document", intValue: nil), CodingKeys(stringValue: "fills", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"color\", …
```

Only convert solid fills to colors

---

CONFIG.md
Sources/FigmaAPI/FigmaClient.swift
Sources/FigmaExport/Input/Params.swift
Sources/FigmaExport/Resources/androidConfig.swift
Sources/FigmaExport/Resources/iOSConfig.swift
Sources/FigmaExport/Subcommands/ExportColors.swift
Sources/FigmaExport/Subcommands/ExportIcons.swift
Sources/FigmaExport/Subcommands/ExportImages.swift
Sources/FigmaExport/Subcommands/ExportTypography.swift

Our Figma file has too many assets. The default timeout is not enough for us to get all assets.
- Add timeout option to change default request timeout.

Added timeout options

---

Examples/Example/UIComponents/Source/LabelStyle.swift
Sources/XcodeExport/XcodeTypographyExporter.swift
Tests/XcodeExportTests/XcodeTypographyExporterTests.swift

Fixed `baselineOffset` calculation.

Fix baselineOffset

---

CONFIG.md
README.md
Sources/FigmaExport/Input/Params.swift
Sources/FigmaExport/Loaders/ColorsLoader.swift
Sources/FigmaExport/Subcommands/ExportColors.swift
Sources/FigmaExportCore/Processor/AssetsProcessor.swift

Resolves #66 
Adds two configuration options to the common:colors: portion of the yaml file. When `useSingleFile` is true, it will only read from the `lightFileId` specified in the figma options. It will look for dark colors as specified by a color style ending in `_dark` (configurable via the `darkModeSuffix` config option).
I wasn't able to write a test for this as the ColorsLoader is hard-wired to hit the Figma API, but I updated the docs and tested things out on my end.

Support exporting colors from a single figma file

---

Tests/FigmaExportTests/AssetsProcessorTests.swift

Realized we can add some tests because the asset processor just deals with raw types. Let me know if you can imagine any other cases to try. This covers the basics.

Add tests for universal asset light and dark asset processor cases

---

.gitignore
CONFIG.md
Sources/FigmaExport/Input/Params.swift
Sources/FigmaExport/Loaders/ImagesLoader.swift

There are no phones with a 1x display scale supporting the latest OS versions. So, we don't have to download 1x assets. This is why I added the `scales` parameter into the config file which gives an ability to choose appropriate scales for your project.
* Sorry for the changes of empty lines. I can revert them if it's necessary.

Add iOS illustration scales to the config file

---

CONFIG.md
Sources/FigmaExport/Input/Params.swift
Sources/FigmaExport/Subcommands/ExportTypography.swift
Sources/FigmaExportCore/Processor/AssetsProcessor.swift
Sources/FigmaExportCore/TextStyle.swift

As mentioned in #77, exporting text styles contained in folders results in invalid names when generating Swift and SwiftUI code. Text styles should allow the same type of configuration for their names as color styles. 
- Added params to the yaml file, similar to color styles
-  `nameValidateRegexp`
- `nameReplaceRegexp`
- `nameStyle`
- Added `TypographyProcessor`
- Process text styles in `ExportTypography`, similar to `ExportColors`
- Added conformance for `Asset` to `TextStyle`
Fixes #77

Allow TextStyle to be processable by an AssetsProcessor

---

Sources/FigmaExport/Loaders/ImagesLoader.swift
Sources/FigmaExport/Output/FileDownloader.swift
Sources/FigmaExportCore/Extensions/Array+chunked.swift

I've found an issue with fetching asset files – if there are many files in a frame, you get the `Request timed out` error after 60 seconds of downloading.
This happens because all file download requests add in a URLSession at the same moment. URLSession has a maximum simultaneous requests count and all requests after this count wait in the queue. And when this is their turn to execute, they have already timed out.
I solved this problem by chunking requests in `FileDownloader`.

Make file download requests chunked

---

CONFIG.md
Sources/AndroidExport/Drawable.swift
Sources/FigmaExport/Input/Params.swift
Sources/FigmaExport/Loaders/ImagesLoader.swift
Sources/FigmaExport/Subcommands/ExportImages.swift

Not in all cases you need to export images in 5 scales, now it is possible to specify custom scales but this option is only available for ios params. I added the scales parameter for android params

Added scales param for Android images export

---

.github/workflows/tests.yml

`shell: bash` adds flags to handle exit codes with errors

Add shell bash to GitHub action test

---

CONFIG.md
Sources/FigmaExport/Input/Params.swift
Sources/FigmaExport/Subcommands/ExportTypography.swift
Sources/XcodeExport/Model/XcodeTypographyOutput.swift
Sources/XcodeExport/XcodeTypographyExporter.swift
Tests/XcodeExportTests/XcodeTypographyExporterTests.swift

In some cases we need to use exported separately from Label, for example - in text field etc.
Added an optional iOS param labelStyleSwift
Added generation of LabelStyle extensions with factory methods for each style
Make LabelStyle public
Updated CONFIG.md

Added possibility of separate text styles extension generation

---

CONFIG.md
README.md
Sources/FigmaExport/Input/Params.swift
Sources/FigmaExport/Loaders/ImagesLoader.swift
Sources/FigmaExport/Resources/iOSConfig.swift
Sources/FigmaExport/Subcommands/ExportIcons.swift
Sources/XcodeExport/Model/XcodeExportExtensions.swift
Sources/XcodeExport/XcodeIconsExporter.swift
Tests/XcodeExportTests/XcodeIconsExporterTests.swift

Adds two configuration options to the common.icons and common.images portion of the yaml file.

Support exporting icons/images from a single figma file

---

CONFIG.md
README.md
Sources/FigmaExport/Input/Params.swift
Sources/FigmaExport/Subcommands/ExportIcons.swift
Sources/XcodeExport/Model/XcodeImagesOutput.swift
Sources/XcodeExport/XcodeIconsExporter.swift

Added 3 new parameters for filtering icons and denote a asset render mode.

Filter icons for render mode

---

CONFIG.md
Sources/FigmaExport/Input/Params.swift
Sources/FigmaExport/Resources/iOSConfig.swift
Sources/FigmaExport/Subcommands/ExportColors.swift
Sources/FigmaExport/Subcommands/ExportIcons.swift
Sources/FigmaExport/Subcommands/ExportImages.swift
Sources/XcodeExport/Model/XcodeColorsOutput.swift
Sources/XcodeExport/Model/XcodeImagesOutput.swift
Sources/XcodeExport/Resources/Bundle+extension.swift.stencil.include
Sources/XcodeExport/Resources/Color+extension.swift.stencil
Sources/XcodeExport/Resources/Image+extension.swift.stencil
Sources/XcodeExport/Resources/UIColor+extension.swift.stencil
Sources/XcodeExport/Resources/UIImage+extension.swift.stencil
Sources/XcodeExport/XcodeColorExporter.swift
Sources/XcodeExport/XcodeImagesExporterBase.swift
Tests/XcodeExportTests/XcodeColorExporterTests.swift
Tests/XcodeExportTests/XcodeIconsExporterTests.swift

Hi, Thank you for an amazing utility!
Fixed SwiftUI preview crashes when accessing assets from a nested Swift Package.
I have two modules the Presentation and the DesignSystem.
The DesignSystem module has Color extension generated by figma-export.
The Presentation module has SwiftUIView that using Color extension of DesignSystem.  As soon as it touches the assets from the DesignSystem module, the preview crashes.
https://developer.apple.com/forums/thread/664295?login=true#reply-to-this-question

Fix SwiftUI preview crashes when accessing assets from a nested Swift Package.

---

Sources/FigmaExportCore/Extensions/StringCase.swift
Tests/FigmaExportCoreTests/Extensions/StringCaseTests.swift

Good time of the day!
I created a small improvement to the way snake case is handled. Right now if you have (for instance) "Icon=WIFI 24" it will be translated into "icon_w_i_f_i_24". With this update it will be "icon_wifi_24", which, I think, is better.
I'm not sure about tests though, haven't found any for this function. Any pointers?

Small improvement for snake case handling

---

Sources/XcodeExport/Resources/Color+extension.swift.stencil
Tests/XcodeExportTests/XcodeColorExporterTests.swift

This change intends expand the usage of the generated SwiftUI color extension.
> Color conforms to a bigger style called ShapeStyle and this allows us to use Colors, Gradients, Materials and more as if they were the same thing. This ShapeStyle protocol is what background uses. This allows us to use these colors everywhere SwiftUI expects a ShapeStyle to be given.
https://www.hackingwithswift.com/books/ios-swiftui/formatting-our-mission-view
Additional discussion about the topic: https://www.hackingwithswift.com/forums/100-days-of-swiftui/extending-shapestyle-for-adding-colors-instead-of-extending-color/12324
I've found that I can create custom templates via `templatesPath` configuration but I still believe that defaulting to this would be better overall.

Modify SwiftUI Color extension to extend ShapeStyle

---

Sources/AndroidExport/Resources/Icons.kt.stencil
Tests/AndroidExportTests/AndroidComposeIconExporterTests.swift

Having null as default simplifies the usage as contentDescription might not always be something a developer wants to add and not having to add null makes life i bit easier

Null as default value for nullable contentDescription

---

Package.resolved
Package.swift
Sources/AndroidExport/AndroidExporter.swift
Sources/XcodeExport/XcodeExporterBase.swift

- Up Stencil version to 0.15.1
- Added [StencilSwiftKit](https://github.com/SwiftGen/StencilSwiftKit/tree/402aaf406b6f0ad70effa2e055b2ea7541fbd100)
Add new nodes & filters dedicated to Swift code generation.

Add StencilSwiftKit

---

Sources/AndroidExport/AndroidColorExporter.swift
Sources/FigmaExport/Input/Params.swift
Sources/FigmaExport/Resources/androidConfig.swift
Sources/FigmaExport/Subcommands/ExportColors.swift
Tests/AndroidExportTests/AndroidColorExporterTests.swift

It is difficult to integrate figma-export into already written project. It usually has own colors.xml file with project-specific color-resources.  And figma-export ouput is hardcorded into colors.xml, so it will conflict with already written file colors.xml. This PR adds optional field to setup output file name (only for colors and only for XML)
Also, devs will ruin autogenerated file cause they already habits to edit colors.xml (I guess autogenerated file should have name like "colors_autogenerated.xml")

Add xmlOutputFileName for androidConfig.colors

---

Sources/FigmaExport/Subcommands/ExportIcons.swift

Hi, I'm using figma-export in our Android team.
I'm very satisfied with this tool. Thank you!
But I'm worried about that every time executing figma-export producing different output of `Icons.kt` because `icons` in `Icons.kt.stencil` contains different ordered items.
So I added `.sorted()` before passing Array to `icons`.
This will produce constant `Icons.kt` file every time.
I will hope you to merge this PR.
Thank you.

Sort icons Array before passing to exportIcons

---

.github/workflows/release.yml
.github/workflows/tests.yml
Sources/XcodeExport/Model/XcodeExportExtensions.swift
Sources/XcodeExport/XcodeColorExporter.swift
Tests/XcodeExportTests/XcodeIconsExporterTests.swift

Fixed Contents.json formatting
