- Sources/FigmaExport/Loaders/ImagesLoader.swift
We got problem when export assets for large project (500+ assets).
The export process failed due to timeout issue. (The timeout is set to 30s)
There also will be a problem if it only uses one api call to pull all images. The request url might be too long.
- Changed to do batch pull images to avoid timeout issue.
> Avoid fetch images timeout issue for large project

- Sources/FigmaAPI/Client.swift
- Sources/FigmaAPI/Endpoint/LatestReleaseEndpoint.swift
- Sources/FigmaAPI/FigmaClient.swift
- Sources/FigmaAPI/GitHubClient.swift
- Sources/FigmaExport/Subcommands/ExportColors.swift
- Sources/FigmaExport/Subcommands/ExportIcons.swift
- Sources/FigmaExport/Subcommands/ExportImages.swift
- Sources/FigmaExport/Subcommands/ExportTypography.swift
- Sources/FigmaExport/Subcommands/checkForUpdate.swift
- Sources/FigmaExport/main.swift
> Check for new version after each action

- README.md
- Sources/FigmaExport/Subcommands/ExportColors.swift
- Sources/FigmaExport/Subcommands/ExportImages.swift
- Sources/FigmaExportCore/Processor/AssetResult.swift
- Sources/FigmaExportCore/Processor/AssetsProcessor.swift
- Sources/FigmaExportCore/Processor/AssetsValidatorError.swift
- Sources/FigmaExportCore/Processor/AssetsValidatorWarning.swift
Resolves #68 
Let me know if there is any fix required for android. I'm not as familiar with how the color specifications work on that platform. I think it can now generate a dark colors file with less values than the light colors file. Is that an issue? For the time being, I've added in the same warning used in iOS. Similarly, I was not able to test illustration exports but let me know if you see any issues there.
> Support universal colors and assets

- Sources/FigmaExport/Loaders/ImagesLoader.swift
- Sources/FigmaExport/Subcommands/ExportIcons.swift
- Sources/FigmaExport/Subcommands/ExportImages.swift
Before
```
2021-03-12T18:18:54+0300 info com.redmadrobot.figma-export : Using FigmaExport 0.21.1 to export images to Android Studio project.
2021-03-12T18:18:54+0300 info com.redmadrobot.figma-export : Fetching images info from Figma. Please wait...
2021-03-12T18:19:03+0300 info com.redmadrobot.figma-export : Processing images...
2021-03-12T18:19:03+0300 info com.redmadrobot.figma-export : Downloading remote files...
2021-03-12T18:19:04+0300 info com.redmadrobot.figma-export.file-downloader : Downloaded 1/30
2021-03-12T18:19:05+0300 info com.redmadrobot.figma-export.file-downloader : Downloaded 2/30
...
```
After:
```
2021-03-12T18:18:54+0300 info com.redmadrobot.figma-export : Using FigmaExport 0.21.1 to export images to Android Studio project.
2021-03-12T18:18:54+0300 info …
```
> Output progress when fetching image URLs

- .github/workflows/tests.yml
- README.md
Documentation: [Adding a workflow status badge](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge)
> Test status badge

- CONFIG.md
- Sources/FigmaExport/Input/Params.swift
- Sources/FigmaExport/Loaders/ImagesLoader.swift
- Sources/FigmaExport/Subcommands/ExportColors.swift
- Sources/FigmaExport/Subcommands/ExportIcons.swift
- Sources/FigmaExport/Subcommands/ExportImages.swift
- Sources/FigmaExport/Subcommands/ExportTypography.swift
> Set ios.colors, ios.icons, ios.images and ios.typography parameters as optional

- CONFIG.md
- Sources/FigmaExport/Input/Params.swift
- Sources/FigmaExport/Subcommands/ExportColors.swift
- Sources/FigmaExportCore/Color.swift
- Sources/FigmaExportCore/Processor/AssetsProcessor.swift
- Sources/XcodeExport/Model/XcodeColorsOutput.swift
- Sources/XcodeExport/Model/XcodeFolderNamespaceContents.swift
- Sources/XcodeExport/XcodeColorExporter.swift
- Tests/FigmaExportTests/AssetsProcessorTests.swift
- Tests/XcodeExportTests/XcodeColorExporterTests.swift
> Add support for iOS color grouping

- Package.swift
- Sources/AndroidExport/AndroidColorExporter.swift
- Tests/AndroidExportTests/AndroidColorExporterTests.swift
> Fix issue with android colors export

- Package.resolved
- Package.swift
- Sources/XcodeExport/XcodeColorExporter.swift
- Sources/XcodeExport/XcodeExporterBase.swift
- Sources/XcodeExport/XcodeIconsExporter.swift
- Sources/XcodeExport/XcodeImagesExporter.swift
- Sources/XcodeExport/XcodeImagesExporterBase.swift
- Tests/XcodeExportTests/XcodeColorExporterTests.swift
- Tests/XcodeExportTests/XcodeIconsExporterTests.swift
> Add keyword escaping in resources name

- Sources/FigmaExport/Subcommands/ExportColors.swift
- Sources/FigmaExport/Subcommands/ExportIcons.swift
- Sources/FigmaExport/Subcommands/ExportImages.swift
- Sources/FigmaExport/Subcommands/ExportTypography.swift
> Fixed an issue when exporting resources to a Swift Package

- Sources/XcodeExport/header.swift
- Tests/XcodeExportTests/header.swift
> Add disable all for swiftlint

- Sources/FigmaExport/Output/VectorDrawableConverter.swift
> Fix path to vd-tool on Apple Silicon Macs

- Sources/FigmaExport/Output/WebpConverter.swift
> Fix path to `cwebp` on Apple Silicon Macs

- Package.resolved
- Package.swift
- Sources/AndroidExport/AndroidColorExporter.swift
- Sources/AndroidExport/AndroidComposeIconExporter.swift
- Sources/AndroidExport/AndroidExporter.swift
- Sources/AndroidExport/AndroidTypographyExporter.swift
- Sources/AndroidExport/Resources/Colors.kt.stencil
- Sources/AndroidExport/Resources/colors.xml.stencil
- Sources/AndroidExport/Resources/typography.xml.stencil
- Sources/XcodeExport/Resources/Color+extension.swift.stencil
- Sources/XcodeExport/Resources/Image+extension.swift.stencil
- Sources/XcodeExport/Resources/Image+extension.swift.stencil.include
- Sources/XcodeExport/Resources/UIColor+extension.swift.stencil
- Sources/XcodeExport/Resources/UIImage+extension.swift.stencil
- Sources/XcodeExport/Resources/UIImage+extension.swift.stencil.include
- Sources/XcodeExport/XcodeColorExporter.swift
- Sources/XcodeExport/XcodeExporterBase.swift
- Sources/XcodeExport/XcodeImagesExporterBase.swift
- Sources/XcodeExport/XcodeTypographyExporter.swift
- Tests/XcodeExportTests/XcodeColorExporterTests.swift
> Use original Stencil instead of fork

- Sources/FigmaExportCore/AssetsFilter.swift
- Sources/XcodeExport/XcodeIconsExporter.swift
- Tests/XcodeExportTests/XcodeIconsExporterTests.swift
> Add support for * symbol for `preservesVectorData`

- README.md
- Sources/FigmaExport/Loaders/ColorsLoader.swift
- Sources/FigmaExport/Subcommands/ExportColors.swift
> Add ability to export specified colors

- Sources/FigmaAPI/Endpoint/ImageEndpoint.swift
- Sources/FigmaExport/Loaders/ImagesLoader.swift
> Fixed a bug when exporting images failed when some image components are empty

- Sources/FigmaExport/Loaders/ImagesLoader.swift
- Sources/FigmaExportCore/Image.swift
- Sources/XcodeExport/XcodeIconsExporter.swift
Fixed image export with suffix for dark mode
Fixed icons export with suffix for renderMode mode (dark mode suffix should be last)
> Fixed image and icons export for iOS with additional suffix

- README.md
- Sources/FigmaExport/Loaders/ImagesLoader.swift
- Sources/FigmaExportCore/Image.swift
- Sources/XcodeExport/Model/XcodeAssetContents.swift
- Sources/XcodeExport/Model/XcodeExportExtensions.swift
From discussions https://github.com/RedMadRobot/figma-export/discussions/133
> [iOS] Support RTL

- README.md
- Sources/FigmaExport/Output/FileDownloader.swift
- Sources/FigmaExport/Output/FileWriter.swift
- Sources/FigmaExport/Subcommands/ExportIcons.swift
- Sources/FigmaExportCore/FileContents.swift
Add android:autoMirrored="true" for xml icon files, If an icon contains "rtl" word in the description field in the properties.
> [Android] Support RTL

- Sources/XcodeExport/Resources/Color+extension.swift.stencil
- Sources/XcodeExport/XcodeColorExporter.swift
- Tests/XcodeExportTests/XcodeColorExporterTests.swift
> Implementation useColorAssets: false for SwiftUI colors

- Sources/FigmaExport/Subcommands/ExportImages.swift
Add templatesPath for ExportImages
> Fix export Illustrations

- Sources/FigmaExportCore/TextStyle.swift
- Sources/XcodeExport/XcodeTypographyExporter.swift
> Fix SwiftUI font style name

- Sources/FigmaExport/Subcommands/ExportColors.swift
> Fix loading colors when common.colors not set
